% spm8w_defaults
% ==============================================================================
% SPM8w r5236
% Script driven batching for SPM8 with additional tools and support for 
% other commonly used analyses (roi, ppi, mixed).
% 
% Heatherton & Kelley Labs
% Last update: February 2013 - DDW
% Created: August, 2010 - DDW
% ==============================================================================
% Edit this file to change the greetings and warning  messages. spm8w uses a 
% custom Stephen Fry toolbox for user messaging. However, if you find yourself
% to be a desipicable person then feel free to edit the defaults. 
% ==============================================================================
% CHANGE LOG:
% =======1=========2=========3=========4=========5=========6=========7=========8

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Naming Conventions
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
bbc.name    = 'Sir';                % Optionally: Madam
%bbc.name   = getenv('USER');       % Will grab your UNIX username. This will
                                    % break on windows and possibly mac.

bbc.filter  = '\d\d\w\w\w\d\d\w\w'; % Regexp filter used for subject selection throughout
                                    % SPM8w. This is rather ridiculously
                                    % important. SPM8w will use this
                                    % internally to find your subject dirs,
                                    % con maps etc. The above Regexp setting
                                    % is for 01jan10aa style naming. As
                                    % long as that string is embedded in
                                    % your naming scheme, spm8w will find it even
                                    % if you have prefixes and suffixes. This
                                    % is the default at Dartmouth.                                  

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Menus
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Text for spm8w.m
bbc.subjects = sprintf('If %s could presently make the selecting of the subjects.',bbc.name);
bbc.pfile    = sprintf('May I trouble %s for the name of a suitable Parameters file?',bbc.name);
bbc.confile  = sprintf(['I believe %s would find it beneficial to provide us with\n'...
                        'the name of a contrast file.'],bbc.name);
bbc.roifile  = sprintf('%s has been most gracious, may I trouble %s further for an ROI file?',bbc.name,bbc.name);
bbc.voifile  = sprintf(['We flog ourselves at having to trouble %s further, however\n'...
                        'there is urgent need of a VOI file.'],bbc.name);
bbc.dfile    = sprintf(['If %s would be so kind as to provide us with a D file, we shall\n'... 
                        'make the necessary arrangements.'],bbc.name);                  

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Errors
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Error message for spm8w.m
bbc.error_subjects     = sprintf(['Pardon me %s, but I couldn''t help but notice the failureness\n'...
                                  'of %s''s selecting of the subjects. Would %s care to try again?'], bbc.name, bbc.name, bbc.name);
bbc.error_pfile        = sprintf(['Excuse me %s, but it behoves me to express the observation that %s\n'...
                                  'has neglected to grace me with the name of a P file... \n'....
                                  'Shall I make %s a fortifying tea?'], bbc.name, bbc.name, bbc.name);
bbc.error_pfile_eval   = sprintf(['It does appear that %s''s P file is temporarily unable to be\n'...
                                  'evaluated. Perphaps %s could find the time to re-examine what \n'....
                                  'was most assuredly a nearly perfect P file creation.'], bbc.name, bbc.name);                         
bbc.error_pfile_path   = sprintf(['If %s could find it inside %s''s most kind and generous heart\n'...
                                  'to grace us with the full and correct path to %s''s P file\n'....
                                  'I will see to it personally that %s''s analysis is swift.'], bbc.name, bbc.name, bbc.name, bbc.name);                         
bbc.error_confile      = sprintf(['Dear me %s, has %s''s fingers fallen victim to a slippage? For\n',...
                                  'it certainly appears that we are in abscence of a con file.'], bbc.name, bbc.name);
bbc.error_confile_eval = sprintf(['I fear we are placed in the impossible situation of having\n'...
                                  'to acknowledge that %s has commited an error in the creation\n'....
                                  'of %s''s con file. Perphaps %s has been drinking?'], bbc.name, bbc.name, bbc.name);                               
bbc.error_roifile      = sprintf(['%s must be of a terrible tiredness, for unless I am gravely \n',...
                                  'mistaken %s has neglected to select an ROI file. Perphaps %s \n',...
                                  'would benifit from a soothing bath?'], bbc.name, bbc.name, bbc.name);   
bbc.error_roifile_eval = sprintf(['While it is generally accepted that %s is infalliable, we cannot\n'...
                                  'help but notice that in this matter %s has made something of a\n'...
                                  'tiny slip as the ROI file fails to evaluate...\n'...
                                  'It shall be our little secret.'], bbc.name, bbc.name);  
bbc.error_voifile      = sprintf(['%s the computer insists that you have failed to selct a VOI file \n',...
                                  'shall we deprive the treasonous machine of electricity?'], bbc.name);   
bbc.error_voifile_eval = sprintf(['%s is beautiful and shiny and incapable of error in all domains of \n',...
                                  'life save one. The creation of an evaluable VOI file. However, this \n'...
                                  'tiny fault only makes %s all the more endearing.'], bbc.name, bbc.name);                                                             
bbc.error_dfile        = sprintf(['The noted abscence of a D file leads me to think %s is in need of \n'...
                                  '%s''s evening gin and tonic?'], bbc.name, bbc.name);   
bbc.error_dfile_eval   = sprintf(['I dread revealing a truth that will no doubt raise %s''s ire, \n'...
                                  'however, the D file %s has submitted is in possesion of an error.'], bbc.name, bbc.name);
bbc.error_prepro       = sprintf(['Dear %s, I hope you will not look too gravely on these matters \n',...
                                  'but it appears that %s''s preprocessing has given up the ghost!'],...
                                   bbc.name, bbc.name);   
bbc.error_compute      = sprintf(['%s! the machines have run amok and are eating %s''s\n',...
                                  'GLM estimation. Oh the treasonous philistines!'],...
                                  bbc.name, bbc.name);   
bbc.error_contrasts    = sprintf(['%s! Come quick, the fish have fallen into the server! \n',...
                                  'And %s''s contrast calculations have been spoiled!'],...
                                  bbc.name, bbc.name);   
bbc.error_rfx          = sprintf(['If I may be allowed to smoothly interrupt %s''s leisure time,\n',...
                                  'there is a matter that requires %s''s most gentle of attentions\n',...
                                  'for it appears that %s''s RFX has run afoul of a failure.'], bbc.name, bbc.name, bbc.name);   
bbc.error_roitool      = sprintf(['If %s would permit my interruption. It appears foreign \n',...
                                  'intelligences have commandered the ROI machinery. May \n',...
                                  'I suggest we pay a visit to the armory?'], bbc.name);   
bbc.error_voitool      = sprintf(['I tremble with shame at having to interrupt %s during %s''s \n',...
                                  'naptime, however foreign intelligences unknown have infiltrated \n',...
                                  'the VOI database. If %s would be so gracious as to update the antivirus'], bbc.name, bbc.name, bbc.name);                          
bbc.error_designtool   = sprintf(['I fear the effect my words may have on %s''s most beautiful coutenance \n',...
                                  'however %s must be alerted to the failing of the Design tool.'], bbc.name, bbc.name);                     
bbc.error_conj         = sprintf(['It is not our custom to pry, but it appears %s \n',...
                                  'is having difficulty with the Conjunction analyses\n',...
                                  'Would %s allow me to contact Thomas Nichols?'], bbc.name, bbc.name);                              
bbc.error_art          = sprintf(['If %s would be so generous as to allow us the priviledge of\n',...
                                  'of borrowing %s''s pistol. We shall step outside and promptly  \n',...
                                  'make an outlier of the ART detection script.'], bbc.name, bbc.name);                                                       
bbc.error_alphasim     = sprintf(['Ahh, I couldn''t but not fail to entirely notice \n',...
                                  'that %s has run afoul of AFNI software. Perhaps %s  \n',...
                                  'would find AlphaSim more useable after a glass of brandy?'], bbc.name, bbc.name);                               
bbc.error_onsetmaker   = sprintf(['%s Darling, I hope %s is well and wonderfully rested. \n',...
                                  'I''ve taken the luxury of fluffing %s''s pillow and suggest\n',...
                                  '%s rest and not trouble %s''s self with making onsets.'], bbc.name, bbc.name, bbc.name,bbc.name,bbc.name);   
bbc.error_nifticonv    = sprintf(['I see that the nifti converter has decided to terminante our little arrangement \n',...
                                  'and has gone rogue, making a mess of %s''s subject files. I shall execute the devil \n',...
                                  'at once.'], bbc.name);  